In [1]:
## Initialized Imports

import os
import requests
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
from MCForecastTools import MCSimulation
import json

%matplotlib inline

load_dotenv()

True

In [15]:
# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

# Create the Alpaca API object
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

# Format current date as ISO format
start = pd.Timestamp("2020-07-10", tz="America/New_York").isoformat()
end = pd.Timestamp("2021-07-10", tz="America/New_York").isoformat()

# Set the tickers
tickers = ["AGG", "SPY","VTI","VTV", "VOE", "VBR", "VEA", "AXP", "AMGN", "AAPL", "BA", "CAT", "CSCO", "CVX", "GS", "HD", "HON", "IBM",
"INTC", "JNJ", "KO", "JPM", "MCD", "MMM", "MRK", "MSFT", "NKE", "PG", 
"TRV", "UNH", "CRM", "VZ", "V", "WBA", "WMT", "DIS", "DOW", "BNDX", "MUB"]

# Set timeframe to one day ('1D') for the Alpaca API
timeframe = "1D"

In [35]:
# Get current closing prices for FB and TWTR
df_portfolio = alpaca.get_barset(
    tickers,
    timeframe,
    start = start,
    end = end
).df

# Display sample data
df_portfolio

                             AAPL                                          \
                             open     high       low     close     volume
time
2021-02-17 00:00:00-05:00  131.25  132.220  129.4700  130.8400   92298227
2021-02-18 00:00:00-05:00  129.20  129.995  127.4100  129.7127   90601312
2021-02-19 00:00:00-05:00  130.24  130.710  128.8000  129.8500   79960220
2021-02-22 00:00:00-05:00  128.01  129.720  125.6000  126.0100   93993093
2021-02-23 00:00:00-05:00  123.76  126.710  118.3900  125.8500  148286878
...                           ...      ...       ...       ...        ...
2021-07-02 00:00:00-04:00  137.92  140.000  137.7450  139.9600   69160944
2021-07-06 00:00:00-04:00  140.10  143.150  140.0700  142.0200   97272256
2021-07-07 00:00:00-04:00  143.54  144.890  142.6600  144.5900   93223232
2021-07-08 00:00:00-04:00  141.57  144.060  140.6650  143.3200   94133450
2021-07-09 00:00:00-04:00  142.73  145.650  142.6522  145.1100   89995907

                                AGG                                       ...  \
                               open      high       low   close   volume  ...
time                                                                      ...
2021-02-17 00:00:00-05:00  116.2200  116.2900  116.1450  116.28  6038386  ...
2021-02-18 00:00:00-05:00  116.1400  116.2800  116.0300  116.20  3910324  ...
2021-02-19 00:00:00-05:00  116.0187  116.0600  115.7515  115.83  4416681  ...
2021-02-22 00:00:00-05:00  115.7600  115.8662  115.4800  115.49  4704520  ...
2021-02-23 00:00:00-05:00  115.7500  115.7500  115.2700  115.52  5373535  ...
...                             ...       ...       ...     ...      ...  ...
2021-07-02 00:00:00-04:00  115.2300  115.3700  115.1700  115.37  4219494  ...
2021-07-06 00:00:00-04:00  115.5100  115.8300  115.5100  115.75  7213127  ...
2021-07-07 00:00:00-04:00  115.8300  116.0150  115.7500  115.95  4455288  ...
2021-07-08 00:00:00-04:00  116.0400  116.1800  115.9600  116.06  5685583  ...
2021-07-09 00:00:00-04:00  115.7350  115.7600  115.6900  115.69  4602694  ...

                             WBA                                      WMT  \
                            open    high     low  close    volume    open
time
2021-02-17 00:00:00-05:00  48.78  49.710  48.600  49.56   4291724  144.65
2021-02-18 00:00:00-05:00  48.88  49.435  48.488  48.91   4169410  139.00
2021-02-19 00:00:00-05:00  49.02  49.500  48.800  48.86   3020364  137.80
2021-02-22 00:00:00-05:00  48.75  49.170  48.400  48.88   3801245  137.74
2021-02-23 00:00:00-05:00  48.60  48.650  47.810  48.41   4192429  137.11
...                          ...     ...     ...    ...       ...     ...
2021-07-02 00:00:00-04:00  49.12  49.140  47.570  48.16  14846993  139.36
2021-07-06 00:00:00-04:00  48.14  48.280  47.220  47.69   7452713  139.93
2021-07-07 00:00:00-04:00  47.59  47.970  47.060  47.50   6614677  139.69
2021-07-08 00:00:00-04:00  47.05  47.090  46.465  46.72   7179356  138.34
2021-07-09 00:00:00-04:00  46.65  47.495  46.650  47.40   5416474  140.41


                             high       low   close    volume
time
2021-02-17 00:00:00-05:00  147.45  144.5000  147.39   7520607
2021-02-18 00:00:00-05:00  140.70  137.5000  137.62  29247194
2021-02-19 00:00:00-05:00  139.42  137.6700  138.37  10911562
2021-02-22 00:00:00-05:00  138.34  136.2500  137.72   9763968
2021-02-23 00:00:00-05:00  137.39  135.0600  135.43   9782767
...                           ...       ...     ...       ...
2021-07-02 00:00:00-04:00  141.08  139.3500  140.13   6971762
2021-07-06 00:00:00-04:00  140.75  139.5150  139.93   5372983
2021-07-07 00:00:00-04:00  141.19  139.3600  139.73   5581966
2021-07-08 00:00:00-04:00  140.65  138.2209  139.60   5620918
2021-07-09 00:00:00-04:00  140.84  139.9300  140.30   4387376

[100 rows x 195 columns]

In [10]:
# Pick the closing prices for the asset classes
df_close = pd.DataFrame()

# fetch closing prices
df_close["AGG"] = df_portfolio["AGG"]["close"]
df_close["SPY"] = df_portfolio["SPY"]["close"]
df_close["VTI"] = df_portfolio["VTI"]["close"]
df_close["VTV"] = df_portfolio["VTV"]["close"]
df_close["VOE"] = df_portfolio["VOE"]["close"]
df_close["VBR"] = df_portfolio["VBR"]["close"]
df_close["VEA"] = df_portfolio["VEA"]["close"]
df_close["AXP"] = df_portfolio["AXP"]["close"]
df_close["AMGN"] = df_portfolio["AMGN"]["close"]
df_close["AAPL"] = df_portfolio["AAPL"]["close"]
df_close["BA"] = df_portfolio["BA"]["close"]
df_close["CAT"] = df_portfolio["CAT"]["close"]
df_close["CSCO"] = df_portfolio["CSCO"]["close"]
df_close["AGG"] = df_portfolio["AGG"]["close"]
df_close["CVX"] = df_portfolio["CVX"]["close"]
df_close["GS"] = df_portfolio["GS"]["close"]
df_close["HD"] = df_portfolio["HD"]["close"]
df_close["HON"] = df_portfolio["HON"]["close"]
df_close["IBM"] = df_portfolio["IBM"]["close"]
df_close["INTC"] = df_portfolio["INTC"]["close"]
df_close["JNJ"] = df_portfolio["JNJ"]["close"]
df_close["KO"] = df_portfolio["KO"]["close"]
df_close["JPM"] = df_portfolio["JPM"]["close"]
df_close["MCD"] = df_portfolio["MCD"]["close"]
df_close["MMM"] = df_portfolio["MMM"]["close"]
df_close["MRK"] = df_portfolio["MRK"]["close"]
df_close["MSFT"] = df_portfolio["MSFT"]["close"]
df_close["NKE"] = df_portfolio["NKE"]["close"]
df_close["PG"] = df_portfolio["PG"]["close"]
df_close["TRV"] = df_portfolio["TRV"]["close"]
df_close["UNH"] = df_portfolio["UNH"]["close"]
df_close["CRM"] = df_portfolio["CRM"]["close"]
df_close["VZ"] = df_portfolio["VZ"]["close"]
df_close["V"] = df_portfolio["V"]["close"]
df_close["WBA"] = df_portfolio["WBA"]["close"]
df_close["WMT"] = df_portfolio["WMT"]["close"]
df_close["DIS"] = df_portfolio["DIS"]["close"]
df_close["DOW"] = df_portfolio["DOW"]["close"]
df_close["BNDX"] = df_portfolio["BNDX"]["close"]
df_close["MUB"] = df_portfolio["MUB"]["close"]



# Drop the time component of the date
df_close.index = df_close.index.date
# Display sample data
df_close

,AGG,SPY,VTI,VTV,VOE,VBR,VEA,AXP,AMGN,AAPL,...,UNH,CRM,VZ,V,WBA,WMT,DIS,DOW,BNDX,MUB
2021-02-17,116.28,392.43,206.74,125.12,127.92,157.45,49.590,128.57,235.46,130.8400,...,326.94,247.67,56.99,207.52,49.56,147.39,186.4300,58.54,57.600,117.260
2021-02-18,116.20,390.75,205.56,124.42,127.13,155.44,49.280,128.49,232.58,129.7127,...,328.51,247.05,56.97,209.41,48.91,137.62,183.0000,57.56,57.530,116.905
2021-02-19,115.83,390.02,205.94,124.86,128.89,158.50,49.490,131.74,231.62,129.8500,...,324.65,246.51,56.45,204.92,48.86,138.37,183.6800,60.40,57.375,116.680
2021-02-22,115.49,387.11,203.97,125.69,129.58,159.60,49.350,135.94,231.48,126.0100,...,327.76,240.96,56.45,208.35,48.88,137.72,191.7600,62.48,57.340,116.180
2021-02-23,115.52,387.50,203.92,126.15,130.09,159.99,49.370,136.95,232.50,125.8500,...,329.60,235.64,57.02,212.14,48.41,135.43,197.0100,62.11,57.305,116.050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-02,115.37,433.75,225.28,138.80,141.69,174.39,51.870,168.51,248.70,139.9600,...,409.41,248.21,56.44,238.63,48.16,140.13,177.0802,63.51,57.210,117.190
2021-07-06,115.75,432.90,224.68,137.38,139.98,171.33,51.530,169.58,243.62,142.0200,...,410.28,250.17,56.41,239.61,47.69,139.93,173.6400,61.95,57.315,117.320
2021-07-07,115.95,434.43,225.08,137.87,140.29,170.95,51.735,170.99,243.23,144.5900,...,411.65,248.35,56.54,240.27,47.50,139.73,172.8200,62.28,57.435,117.465
2021-07-08,116.06,430.95,223.17,136.52,138.66,168.84,50.980,167.51,244.28,143.3200,...,410.20,245.95,55.69,236.72,46.72,139.60,172.8600,61.43,57.430,117.690
2021-07-09,115.69,435.48,225.87,138.52,141.31,173.03,51.870,171.94,245.16,145.1100,...,412.12,245.06,56.07,238.45,47.40,140.30,177.0300,63.10,57.310,117.600

In [12]:
# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

# Create the Alpaca API object
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")
alpaca

In [13]:
# Format current date as ISO format
start = pd.Timestamp("2020-07-10", tz="America/New_York").isoformat()
end = pd.Timestamp("2021-07-10", tz="America/New_York").isoformat()

# Set the tickers
tickers = ["GLD", "BAR", "UGL", "DBP"]

# Set timeframe to '1D' for Alpaca API
timeframe = "1D"

In [14]:
# Get current closing prices for SPY and AGG
df_portfolio_2 = alpaca.get_barset(
    tickers,
    timeframe,
    start = start,
    end = end
).df

# Preview DataFrame
df_portfolio_2

                             BAR                                      DBP  \
                            open     high      low   close  volume   open
time
2021-02-17 00:00:00-05:00  17.69  17.7389  17.5900  17.635  422768  50.28
2021-02-18 00:00:00-05:00  17.70  17.7300  17.5711  17.630  270499  50.31
2021-02-19 00:00:00-05:00  17.66  17.8000  17.6600  17.700  344937  50.22
2021-02-22 00:00:00-05:00  17.86  18.0150  17.8450  17.980  372080  50.63
2021-02-23 00:00:00-05:00  17.96  17.9900  17.8500  17.930  348136  51.15
...                          ...      ...      ...     ...     ...    ...
2021-07-02 00:00:00-04:00  17.77  17.7999  17.6600  17.760  325957  49.84
2021-07-06 00:00:00-04:00  17.95  18.0000  17.7900  17.850  288703  50.30
2021-07-07 00:00:00-04:00  17.91  17.9600  17.8500  17.905  304676  50.13
2021-07-08 00:00:00-04:00  18.02  18.0100  17.8200  17.900  187830  50.30
2021-07-09 00:00:00-04:00  17.92  18.0000  17.9019  17.960  293683  49.78

                                                                 GLD           \
                              high      low    close  volume    open     high
time
2021-02-17 00:00:00-05:00  50.3000  49.9626  50.0550    5377  166.92  167.340
2021-02-18 00:00:00-05:00  50.3100  49.9180  49.9400    4086  166.98  167.300
2021-02-19 00:00:00-05:00  50.5011  50.1301  50.2213    4057  166.76  167.940
2021-02-22 00:00:00-05:00  51.2100  50.6300  51.1700    3387  168.54  169.890
2021-02-23 00:00:00-05:00  51.1500  50.6800  50.7800    8741  169.48  169.740
...                            ...      ...      ...     ...     ...      ...
2021-07-02 00:00:00-04:00  49.8600  49.5801  49.8600    5890  167.35  167.715
2021-07-06 00:00:00-04:00  50.3000  49.7600  49.7600  130380  169.27  169.650
2021-07-07 00:00:00-04:00  50.1300  49.9355  49.9500    6381  168.72  169.230
2021-07-08 00:00:00-04:00  50.3000  49.6900  49.7799    3461  169.82  169.855
2021-07-09 00:00:00-04:00  50.2000  49.7800  50.1000    7874  168.84  169.620

                                                       UGL                    \
                              low   close    volume   open     high      low
time
2021-02-17 00:00:00-05:00  165.85  166.32  10699567  58.96  59.2300  58.1500
2021-02-18 00:00:00-05:00  165.73  166.32   6943475  58.93  59.1200  58.0800
2021-02-19 00:00:00-05:00  166.60  167.00   7479035  58.79  59.6300  58.6600
2021-02-22 00:00:00-05:00  168.30  169.47   9253534  60.01  61.0321  59.9386
2021-02-23 00:00:00-05:00  168.28  169.12   8237885  60.73  60.9000  59.9300
...                           ...     ...       ...    ...      ...      ...
2021-07-02 00:00:00-04:00  166.40  167.32   6306689  58.42  58.6200  57.7500
2021-07-06 00:00:00-04:00  167.54  168.12   7214071  59.68  59.9774  58.5599
2021-07-07 00:00:00-04:00  168.19  168.78   6626651  59.32  59.6500  58.9300
2021-07-08 00:00:00-04:00  167.91  168.67   6747318  60.11  60.1400  58.6800
2021-07-09 00:00:00-04:00  168.66  169.20   4619133  59.38  59.9500  59.2790


                             close  volume
time
2021-02-17 00:00:00-05:00  58.5400  200462
2021-02-18 00:00:00-05:00  58.4850  179718
2021-02-19 00:00:00-05:00  58.9800  170922
2021-02-22 00:00:00-05:00  60.7500  155764
2021-02-23 00:00:00-05:00  60.5299  126433
...                            ...     ...
2021-07-02 00:00:00-04:00  58.3200  113931
2021-07-06 00:00:00-04:00  58.9500  162807
2021-07-07 00:00:00-04:00  59.3800  124083
2021-07-08 00:00:00-04:00  59.3000  184356
2021-07-09 00:00:00-04:00  59.6700   75157

[100 rows x 20 columns]

In [17]:
# Pick AGG and SPY close prices
df_closing_prices = pd.DataFrame()

# fetch closing prices
df_closing_prices["GLD"] = df_portfolio_2["GLD"]["close"]
df_closing_prices["BAR"] = df_portfolio_2["BAR"]["close"]
df_closing_prices["UGL"] = df_portfolio_2["UGL"]["close"]
df_closing_prices["DBP"] = df_portfolio_2["DBP"]["close"]


# Drop the time component of the date
df_closing_prices.index = df_closing_prices.index.date

# Display sample data
df_closing_prices

               GLD     BAR      UGL      DBP
2021-02-17  166.32  17.635  58.5400  50.0550
2021-02-18  166.32  17.630  58.4850  49.9400
2021-02-19  167.00  17.700  58.9800  50.2213
2021-02-22  169.47  17.980  60.7500  51.1700
2021-02-23  169.12  17.930  60.5299  50.7800
...            ...     ...      ...      ...
2021-07-02  167.32  17.760  58.3200  49.8600
2021-07-06  168.12  17.850  58.9500  49.7600
2021-07-07  168.78  17.905  59.3800  49.9500
2021-07-08  168.67  17.900  59.3000  49.7799
2021-07-09  169.20  17.960  59.6700  50.1000

[100 rows x 4 columns]

In [39]:
# Data Cleaning 

## Concatenating all dataframes to merge columns into a single dataframe 
df_final = pd.concat([df_closing_prices,df_close], axis= 'columns', join='outer')

## Identified and dropped null records in the combined portfolio
df_final = df_final.dropna()

## Dropped duplicates in the combined protfolio
df_final = df_final.drop_duplicates()

df_final.head()

,GLD,BAR,UGL,DBP,AGG,SPY,VTI,VTV,VOE,VBR,...,UNH,CRM,VZ,V,WBA,WMT,DIS,DOW,BNDX,MUB
2021-02-17,166.32,17.635,58.5400,50.0550,116.28,392.43,206.74,125.12,127.92,157.45,...,326.94,247.67,56.99,207.52,49.56,147.39,186.43,58.54,57.600,117.260
2021-02-18,166.32,17.630,58.4850,49.9400,116.20,390.75,205.56,124.42,127.13,155.44,...,328.51,247.05,56.97,209.41,48.91,137.62,183.00,57.56,57.530,116.905
2021-02-19,167.00,17.700,58.9800,50.2213,115.83,390.02,205.94,124.86,128.89,158.50,...,324.65,246.51,56.45,204.92,48.86,138.37,183.68,60.40,57.375,116.680
2021-02-22,169.47,17.980,60.7500,51.1700,115.49,387.11,203.97,125.69,129.58,159.60,...,327.76,240.96,56.45,208.35,48.88,137.72,191.76,62.48,57.340,116.180
2021-02-23,169.12,17.930,60.5299,50.7800,115.52,387.50,203.92,126.15,130.09,159.99,...,329.60,235.64,57.02,212.14,48.41,135.43,197.01,62.11,57.305,116.050